ALTER TABLE photos ADD COLUMN camera TEXT NOT NULL DEFAULT '';
ALTER TABLE photos ADD COLUMN lens TEXT NOT NULL DEFAULT '';
ALTER TABLE photos ADD COLUMN technical TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS geocode_cache (
  cache_key TEXT PRIMARY KEY,
  location TEXT NOT NULL,
  created_at INTEGER NOT NULL
);
