ALTER TABLE photos ADD COLUMN thumbnail_key TEXT NOT NULL DEFAULT '';
ALTER TABLE photos ADD COLUMN thumbnail_version TEXT NOT NULL DEFAULT '';
ALTER TABLE photos ADD COLUMN thumbnail_content_type TEXT NOT NULL DEFAULT '';
ALTER TABLE photos ADD COLUMN thumbnail_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE photos ADD COLUMN width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE photos ADD COLUMN height INTEGER NOT NULL DEFAULT 0;
